"use client";

import { useState } from "react";
import { ClipboardCopy } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { useBlockCache } from "@/lib/contexts/block-cache-context";
import { parseDayImport } from "@/lib/import/parse";
import type { Day } from "@/lib/types/database";

const DAY_PROMPT = `Generate training day JSON for LiftLog. Use exactly this schema:

{
  "name": "string (optional)",
  "week_day_index": 0-6 or null (0=Mon, 6=Sun),
  "columns": ["Exercise", "Sets", "Reps", "Weight", "RPE"],
  "rows": [["exercise name", "sets", "reps", "weight", "rpe"], ...]
}

Rules:
- columns is an array of column header strings
- rows is an array of arrays; each inner array matches the columns order
- all values are strings
- Output only valid JSON, no explanation`;

interface ImportDayDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  weekId: string;
  onDayImported?: (day: Day) => void;
}

export function ImportDayDialog({
  open,
  onOpenChange,
  weekId,
  onDayImported,
}: ImportDayDialogProps) {
  const { importDay } = useBlockCache();
  const [json, setJson] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [copied, setCopied] = useState(false);

  function handleOpenChange(next: boolean) {
    onOpenChange(next);
    if (!next) {
      setJson("");
      setError(null);
      setPreview(null);
    }
  }

  async function handleCopyPrompt() {
    await navigator.clipboard.writeText(DAY_PROMPT);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleImport() {
    setError(null);
    setPreview(null);

    let parsed;
    try {
      parsed = parseDayImport(JSON.parse(json));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Invalid JSON");
      return;
    }

    const rowCount = parsed.rows.length;
    const colCount = parsed.columns.length;
    setPreview(`${colCount} column(s), ${rowCount} row(s)`);

    setIsImporting(true);
    const day = await importDay(weekId, parsed);
    setIsImporting(false);

    if (!day) {
      setError("Failed to import day. Please try again.");
      return;
    }

    onDayImported?.(day);
    handleOpenChange(false);
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Import Day</DialogTitle>
          <DialogDescription>
            Paste JSON generated by an AI assistant to create a training day.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleCopyPrompt}
            className="gap-2"
          >
            <ClipboardCopy size={14} />
            {copied ? "Copied!" : "Copy AI prompt"}
          </Button>

          <Textarea
            value={json}
            onChange={(e) => {
              setJson(e.target.value);
              setError(null);
              setPreview(null);
            }}
            placeholder='{"columns": ["Exercise", "Sets", "Reps"], "rows": [["Squat", "3", "5"]]}'
            className="min-h-[180px] font-mono text-xs"
          />

          {preview && (
            <p className="text-sm text-muted-foreground">{preview}</p>
          )}
          {error && <p className="text-sm text-destructive">{error}</p>}
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => handleOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleImport}
            disabled={isImporting || !json.trim()}
          >
            {isImporting ? "Importing..." : "Import"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
