"use client";

import { useState } from "react";
import { ClipboardCopy } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { useBlockCache } from "@/lib/contexts/block-cache-context";
import { parseWeekImport } from "@/lib/import/parse";
import type { Week } from "@/lib/types/database";

const WEEK_PROMPT = `Generate a training week JSON for LiftLog. Use exactly this schema:

{
  "days": [
    {
      "name": "string (optional)",
      "week_day_index": 0-6 or null (0=Mon, 6=Sun),
      "columns": ["Exercise", "Sets", "Reps", "Weight", "RPE"],
      "rows": [
        ["exercise name", "sets", "reps", "weight", "rpe"],
        { "separator": "Section Label" },
        ["exercise name", "sets", "reps", "weight", "rpe"]
      ]
    }
  ]
}

Rules:
- days is an array of day objects
- columns is an array of column header strings
- rows is an array where each item is either:
  - a string array matching the columns order (a regular exercise row)
  - an object { "separator": "label" } to insert a labeled section divider
- all cell values are strings
- Output only valid JSON, no explanation`;

interface ImportWeekDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onWeekImported?: (week: Week) => void;
}

export function ImportWeekDialog({
  open,
  onOpenChange,
  onWeekImported,
}: ImportWeekDialogProps) {
  const { importWeek } = useBlockCache();
  const [json, setJson] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [copied, setCopied] = useState(false);

  function handleOpenChange(next: boolean) {
    onOpenChange(next);
    if (!next) {
      setJson("");
      setError(null);
      setPreview(null);
    }
  }

  async function handleCopyPrompt() {
    await navigator.clipboard.writeText(WEEK_PROMPT);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleImport() {
    setError(null);
    setPreview(null);

    let parsed;
    try {
      parsed = parseWeekImport(JSON.parse(json));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Invalid JSON");
      return;
    }

    const dayCount = parsed.days.length;
    const totalRows = parsed.days.reduce((sum, d) => sum + d.rows.length, 0);
    setPreview(`${dayCount} day(s), ${totalRows} total rows`);

    setIsImporting(true);
    const week = await importWeek(parsed);
    setIsImporting(false);

    if (!week) {
      setError("Failed to import week. Please try again.");
      return;
    }

    onWeekImported?.(week);
    handleOpenChange(false);
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Import Week</DialogTitle>
          <DialogDescription>
            Paste JSON generated by an AI assistant to create a full training week.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleCopyPrompt}
            className="gap-2"
          >
            <ClipboardCopy size={14} />
            {copied ? "Copied!" : "Copy AI prompt"}
          </Button>

          <Textarea
            value={json}
            onChange={(e) => {
              setJson(e.target.value);
              setError(null);
              setPreview(null);
            }}
            placeholder='{"days": [{"columns": ["Exercise", "Sets", "Reps"], "rows": [["Squat", "3", "5"]]}]}'
            className="min-h-[180px] font-mono text-xs"
          />

          {preview && (
            <p className="text-sm text-muted-foreground">{preview}</p>
          )}
          {error && <p className="text-sm text-destructive">{error}</p>}
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => handleOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleImport}
            disabled={isImporting || !json.trim()}
          >
            {isImporting ? "Importing..." : "Import"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
