"use client";

import { useState } from "react";
import { ClipboardCopy } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { createTables } from "@/lib/db";
import { ImportEngine } from "@/lib/engines/import-engine";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { parseBlockImport } from "@/lib/import/parse";
import type { Block } from "@/lib/types/database";

const BLOCK_PROMPT = `Generate a training block JSON for LiftLog. Use exactly this schema:

{
  "name": "string (required)",
  "start_date": "YYYY-MM-DD (optional)",
  "weeks": [
    {
      "days": [
        {
          "name": "string (optional)",
          "week_day_index": 0-6 or null (0=Mon, 6=Sun),
          "columns": ["Exercise", "Sets", "Reps", "Weight", "RPE"],
          "rows": [
            ["exercise name", "sets", "reps", "weight", "rpe"],
            { "separator": "Section Label" },
            ["exercise name", "sets", "reps", "weight", "rpe"]
          ]
        }
      ]
    }
  ]
}

Rules:
- name is required
- columns is an array of column header strings
- rows is an array where each item is either:
  - a string array matching the columns order (a regular exercise row)
  - an object { "separator": "label" } to insert a labeled section divider
- all cell values are strings
- Output only valid JSON, no explanation`;

interface ImportBlockDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  programId: string;
  nextBlockOrder: number;
  onBlockImported: (block: Block) => void;
}

export function ImportBlockDialog({
  open,
  onOpenChange,
  programId,
  nextBlockOrder,
  onBlockImported,
}: ImportBlockDialogProps) {
  const [json, setJson] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [copied, setCopied] = useState(false);

  function handleOpenChange(next: boolean) {
    onOpenChange(next);
    if (!next) {
      setJson("");
      setError(null);
      setPreview(null);
    }
  }

  async function handleCopyPrompt() {
    await navigator.clipboard.writeText(BLOCK_PROMPT);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleImport() {
    setError(null);
    setPreview(null);

    let parsed;
    try {
      parsed = parseBlockImport(JSON.parse(json));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Invalid JSON");
      return;
    }

    const weekCount = parsed.weeks.length;
    const dayCount = parsed.weeks.reduce((sum, w) => sum + w.days.length, 0);
    const totalRows = parsed.weeks.reduce(
      (sum, w) => sum + w.days.reduce((s, d) => s + d.rows.length, 0),
      0,
    );
    setPreview(`${weekCount} week(s), ${dayCount} day(s), ${totalRows} total rows`);

    setIsImporting(true);

    try {
      const supabase = createClient();
      const tables = createTables(supabase);
      const engine = new ImportEngine(tables);
      const result = await engine.importBlock(programId, nextBlockOrder, parsed);

      setIsImporting(false);
      onBlockImported(result.block);
      handleOpenChange(false);
    } catch {
      setError("Failed to create block. Please try again.");
      setIsImporting(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Import Block</DialogTitle>
          <DialogDescription>
            Paste JSON generated by an AI assistant to create a full training block with weeks and days.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleCopyPrompt}
            className="gap-2"
          >
            <ClipboardCopy size={14} />
            {copied ? "Copied!" : "Copy AI prompt"}
          </Button>

          <Textarea
            value={json}
            onChange={(e) => {
              setJson(e.target.value);
              setError(null);
              setPreview(null);
            }}
            placeholder='{"name": "Hypertrophy Block", "weeks": [{"days": [{"columns": ["Exercise", "Sets", "Reps"], "rows": [["Squat", "3", "5"]]}]}]}'
            className="min-h-[180px] font-mono text-xs"
          />

          {preview && (
            <p className="text-sm text-muted-foreground">{preview}</p>
          )}
          {error && <p className="text-sm text-destructive">{error}</p>}
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => handleOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleImport}
            disabled={isImporting || !json.trim()}
          >
            {isImporting ? "Importing..." : "Import"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
